version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "4200:80"   # Map localhost:4200 to Nginx port 80
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
